In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
import pprint


from imblearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV, KFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from imblearn.under_sampling import RandomUnderSampler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

from JusticeModel import JusticeModel

plt.style.use('fivethirtyeight')
warnings.filterwarnings('ignore')


## Try Predicting by Case

In [2]:
justices = ['alito', 'breyer', 'kagan', 'kavanaugh', 'ginsburg', 'gorsuch', 'roberts', 'sotomayor', 'thomas']
justice_models = []
for justice in justices:
    model = SVC(degree=2, 
                  gamma='auto', 
                  kernel='poly')
    
    jm = JusticeModel(justice, mode='crossval', model=model)
    jm.fit(balance_method=None)
    justice_models.append(jm)

Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.
Model trained successfully.


In [3]:
true_votes = []
pred_votes = []

for justice, model in zip(justices, justice_models):
    fpath = 'data/test/%s.csv' % justice.capitalize()
    test_data = pd.read_csv(fpath)
    X = test_data['cleanText'].fillna(' ').to_numpy()
    y_true = test_data['vote'].to_numpy()
    
    y_pred = model.predict(X)
    
    true_votes.append(y_true)
    pred_votes.append(y_pred)

In [4]:
true_votes

[array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 0, 0, 1, 1]),
 array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1]),
 array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1]),
 array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1]),
 array([0, 1, 1, 1, 1, 1, 1, 0, 1, 1])]

In [5]:
pred_votes

[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]

In [13]:
pd.read_csv('data/test/Alito.csv').loc[1]['vote']

1

In [14]:
pd.read_csv('data/test/Breyer.csv').loc[1]['vote']

1

In [15]:
pd.read_csv('data/test/Gorsuch.csv').loc[1]['vote']

1